name: Continuous training
on:
  push:
    branches: [ release/workflow-continuous-training/issue-01 ]
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running the workflow'
        required: false
        default: 'Manually triggered'

jobs:
  continuous-training:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Create and setup virtualenv
        run: |
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip

      - name: Install dependencies
        run: |
          source env/bin/activate
          pip install dvc
          pip install dvc-azure
          pip install -r src/requirements.txt

      - name: Azure login
        uses: azure/login@v2.1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Run train
        run: |
          source env/bin/activate
          dvc pull model/model.pkl -r model-track
          dvc pull model/scaler.pkl -r model-track
          dvc unprotect model/model.pkl
          dvc unprotect model/scaler.pkl
          dvc repro -f
          echo "Model training completed"
          dvc add model/model.pkl -r model-track --to-remote
          dvc push model/model.pkl -r model-track
          dvc add model/scaler.pkl -r model-track --to-remote
          dvc push model/scaler.pkl -r model-track

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          commit_message: 'chore: Update model serialized files'
          commit_user_name: Juan Gallego [GitHub Actions]
          commit_user_email: juancamilogallego70@icloud.com
          commit_author: 0xCamiX

      - name: Push metrics
        uses: iterative/setup-cml@v2
        run: |
          cat reports/scores.txt >> reports/scores.md 
          cml-publish model_performance.png --md >> report.md
          cml-send-comment reports/report.md 


