name: Continuous training
on:
  push:
    branches:
      - 'release/workflow-continuous-training/issue-01'
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running the workflow'
        required: false
        default: 'Manually triggered'

jobs:
  continuous-training:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.9'

      - name: Create and setup virtualenv
        run: |
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip

      - name: Install dependencies
        run: |
          source env/bin/activate
          pip install -r src/requirements.txt

      - name: Azure login
        uses: azure/login@v2.1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Run train
        run: |
          source env/bin/activate
          dvc pull model/model.pkl -r model-track
          dvc pull model/scaler.pkl -r model-track
          dvc unprotect model/model.pkl
          dvc unprotect model/scaler.pkl
          dvc repro -f