name: Continuous Training
on: [push]
jobs:
  continuous-training:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Create and setup virtualenv
        run: |
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip

      - name: Install dependencies
        run: |
          source env/bin/activate
          pip install dvc
          pip install dvc-azure
          pip install -r src/requirements.txt
          echo "Installed dependencies"