name: Testing API

on: [push, pull_request]

jobs:
  testing-api:
    runs-on: ubuntu-latest

    env:
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Creating and setup virtualenv
        run: |
          pip install virtualenv
          virtualenv env
          source venv/bin/activate

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install pip
          pip install dvc-azure
          pip install -r api/requirements.txt

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run tests
        run: |
          dvc pull model/model.pkl -r model-track
          pytest tests/*_test.py
