name: Testing API

on: [push, pull_request]

jobs:
  testing-api:
    runs-on: ubuntu-latest

    env:
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Create and setup virtualenv
        run: |
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip

      - name: Install dependencies
        run: |
          source env/bin/activate
          pip install dvc
          pip install dvc-azure
          pip install -r api/requirements.txt

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run tests
        run: |
          source env/bin/activate
          dvc pull model/model.pkl -r model-track
          pytest tests/*_test.py
